spring.application.name=enotes-keeper



#spring.datasource.url=jdbc:mysql://localhost:3306/enotes_db
#spring.datasource.username=root
#spring.datasource.password=1234

spring.datasource.url=jdbc:postgresql://dpg-d7bdntk9c44c73alujqg-a:5432/enotes_db_9vvb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=enotes_db_9vvb_user
spring.datasource.password=0iMyJaVReNAmgmgo18l0vtK0aloxVUPl
#spring.profiles.active=docker
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

spring.thymeleaf.cache=false
server.port=8080
